/**
 * Maps country names to their currency codes
 * This is a comprehensive mapping of countries to their currencies
 */
export function getCurrencyFromCountry(countryName: string): string {
  const countryToCurrency: Record<string, string> = {
    // African countries
    'Nigeria': 'NGN',
    'Ghana': 'GHS',
    'Kenya': 'KES',
    'South Africa': 'ZAR',
    'Tanzania': 'TZS',
    'Uganda': 'UGX',
    'Zimbabwe': 'USD',
    'Zambia': 'ZMW',
    'Botswana': 'BWP',
    'Namibia': 'NAD',
    'Mozambique': 'MZN',
    'Angola': 'AOA',
    'Ethiopia': 'ETB',
    'Egypt': 'EGP',
    'Morocco': 'MAD',
    'Algeria': 'DZD',
    'Tunisia': 'TND',
    'Senegal': 'XOF',
    'Ivory Coast': 'XOF',
    'Cameroon': 'XAF',
    'Gabon': 'XAF',
    'Congo': 'XAF',
    'DR Congo': 'CDF',
    'Rwanda': 'RWF',
    'Burundi': 'BIF',
    'Malawi': 'MWK',
    'Mauritius': 'MUR',
    'Seychelles': 'SCR',
    'Madagascar': 'MGA',
    'Mauritania': 'MRU',
    'Niger': 'XOF',
    'Burkina Faso': 'XOF',
    'Mali': 'XOF',
    'Guinea': 'GNF',
    'Sierra Leone': 'SLL',
    'Liberia': 'LRD',
    'Gambia': 'GMD',
    'Guinea-Bissau': 'XOF',
    'Cape Verde': 'CVE',
    'São Tomé and Príncipe': 'STN',
    'Equatorial Guinea': 'XAF',
    'Chad': 'XAF',
    'Central African Republic': 'XAF',
    'Sudan': 'SDG',
    'South Sudan': 'SSP',
    'Eritrea': 'ERN',
    'Djibouti': 'DJF',
    'Somalia': 'SOS',
    'Libya': 'LYD',
    'Benin': 'XOF',
    'Togo': 'XOF',
    'Comoros': 'KMF',
    
    // Major world currencies
    'United States': 'USD',
    'United Kingdom': 'GBP',
    'Canada': 'CAD',
    'Australia': 'AUD',
    'New Zealand': 'NZD',
    'Japan': 'JPY',
    'China': 'CNY',
    'India': 'INR',
    'Brazil': 'BRL',
    'Mexico': 'MXN',
    'Argentina': 'ARS',
    'Chile': 'CLP',
    'Colombia': 'COP',
    'Peru': 'PEN',
    'Venezuela': 'VES',
    'Ecuador': 'USD',
    'Panama': 'USD',
    'El Salvador': 'USD',
    
    // European countries
    'Germany': 'EUR',
    'France': 'EUR',
    'Italy': 'EUR',
    'Spain': 'EUR',
    'Netherlands': 'EUR',
    'Belgium': 'EUR',
    'Austria': 'EUR',
    'Portugal': 'EUR',
    'Greece': 'EUR',
    'Ireland': 'EUR',
    'Finland': 'EUR',
    'Sweden': 'SEK',
    'Denmark': 'DKK',
    'Norway': 'NOK',
    'Switzerland': 'CHF',
    'Poland': 'PLN',
    'Czech Republic': 'CZK',
    'Hungary': 'HUF',
    'Romania': 'RON',
    'Bulgaria': 'BGN',
    'Croatia': 'EUR',
    'Serbia': 'RSD',
    'Ukraine': 'UAH',
    'Russia': 'RUB',
    'Turkey': 'TRY',
    
    // Middle East
    'Saudi Arabia': 'SAR',
    'United Arab Emirates': 'AED',
    'Qatar': 'QAR',
    'Kuwait': 'KWD',
    'Bahrain': 'BHD',
    'Oman': 'OMR',
    'Jordan': 'JOD',
    'Lebanon': 'LBP',
    'Israel': 'ILS',
    'Iran': 'IRR',
    'Iraq': 'IQD',
    'Yemen': 'YER',
    'Syria': 'SYP',
    
    // Asia
    'Singapore': 'SGD',
    'Malaysia': 'MYR',
    'Thailand': 'THB',
    'Indonesia': 'IDR',
    'Philippines': 'PHP',
    'Vietnam': 'VND',
    'South Korea': 'KRW',
    'Taiwan': 'TWD',
    'Hong Kong': 'HKD',
    'Pakistan': 'PKR',
    'Bangladesh': 'BDT',
    'Sri Lanka': 'LKR',
    'Nepal': 'NPR',
    'Myanmar': 'MMK',
    'Cambodia': 'KHR',
    'Laos': 'LAK',
    'Mongolia': 'MNT',
    'Kazakhstan': 'KZT',
    'Uzbekistan': 'UZS',
    'Kyrgyzstan': 'KGS',
    'Tajikistan': 'TJS',
    'Turkmenistan': 'TMT',
    'Afghanistan': 'AFN',
    
    // Oceania
    'Fiji': 'FJD',
    'Papua New Guinea': 'PGK',
    'Solomon Islands': 'SBD',
    'Vanuatu': 'VUV',
    'New Caledonia': 'XPF',
    'French Polynesia': 'XPF',
    
    // Caribbean
    'Jamaica': 'JMD',
    'Trinidad and Tobago': 'TTD',
    'Barbados': 'BBD',
    'Bahamas': 'BSD',
    'Belize': 'BZD',
    'Guyana': 'GYD',
    'Suriname': 'SRD',
    
    // Default fallback
    'Other': 'CAD',
  }

  // Normalize country name (trim, capitalize first letter of each word)
  const normalized = countryName
    .trim()
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')

  return countryToCurrency[normalized] || countryToCurrency[countryName] || 'USD'
}

/**
 * Gets currency symbol for a currency code
 */
export function getCurrencySymbol(currencyCode: string): string {
  const currencySymbols: Record<string, string> = {
    'NGN': '₦',
    'GHS': '₵',
    'KES': 'KSh',
    'USD': '$',
    'EUR': '€',
    'GBP': '£',
    'JPY': '¥',
    'CNY': '¥',
    'INR': '₹',
    'ZAR': 'R',
    'CAD': 'C$',
    'AUD': 'A$',
    'NZD': 'NZ$',
    'BRL': 'R$',
    'MXN': '$',
    'ARS': '$',
    'CLP': '$',
    'COP': '$',
    'PEN': 'S/',
    'VES': 'Bs',
    'CHF': 'CHF',
    'SEK': 'kr',
    'DKK': 'kr',
    'NOK': 'kr',
    'PLN': 'zł',
    'CZK': 'Kč',
    'HUF': 'Ft',
    'RON': 'lei',
    'BGN': 'лв',
    'RSD': 'дин',
    'UAH': '₴',
    'RUB': '₽',
    'TRY': '₺',
    'SAR': '﷼',
    'AED': 'د.إ',
    'QAR': '﷼',
    'KWD': 'د.ك',
    'BHD': '.د.ب',
    'OMR': '﷼',
    'JOD': 'د.ا',
    'LBP': '£',
    'ILS': '₪',
    'IRR': '﷼',
    'IQD': 'ع.د',
    'YER': '﷼',
    'SYP': '£',
    'SGD': 'S$',
    'MYR': 'RM',
    'THB': '฿',
    'IDR': 'Rp',
    'PHP': '₱',
    'VND': '₫',
    'KRW': '₩',
    'TWD': 'NT$',
    'HKD': 'HK$',
    'PKR': '₨',
    'BDT': '৳',
    'LKR': 'Rs',
    'NPR': '₨',
    'MMK': 'K',
    'KHR': '៛',
    'LAK': '₭',
    'MNT': '₮',
    'KZT': '₸',
    'UZS': 'лв',
    'KGS': 'лв',
    'TJS': 'ЅМ',
    'TMT': 'm',
    'AFN': '؋',
    'FJD': 'FJ$',
    'PGK': 'K',
    'SBD': 'SI$',
    'VUV': 'Vt',
    'XPF': '₣',
    'JMD': 'J$',
    'TTD': 'TT$',
    'BBD': 'Bds$',
    'BSD': 'B$',
    'BZD': 'BZ$',
    'GYD': 'GY$',
    'SRD': 'Sr$',
    'TZS': 'TSh',
    'UGX': 'USh',
    'ZMW': 'ZK',
    'BWP': 'P',
    'NAD': 'N$',
    'MZN': 'MT',
    'AOA': 'Kz',
    'ETB': 'Br',
    'EGP': 'E£',
    'MAD': 'د.م.',
    'DZD': 'د.ج',
    'TND': 'د.ت',
    'XOF': 'CFA',
    'XAF': 'FCFA',
    'CDF': 'FC',
    'RWF': 'RF',
    'BIF': 'FBu',
    'MWK': 'MK',
    'MUR': '₨',
    'SCR': '₨',
    'MGA': 'Ar',
    'MRU': 'UM',
    'GNF': 'FG',
    'SLL': 'Le',
    'LRD': 'L$',
    'GMD': 'D',
    'CVE': 'Esc',
    'STN': 'Db',
    'SDG': 'ج.س.',
    'SSP': 'SS£',
    'ERN': 'Nfk',
    'DJF': 'Fdj',
    'SOS': 'Sh',
    'LYD': 'ل.د',
    'KMF': 'CF',
  }

  return currencySymbols[currencyCode] || currencyCode
}

